name = "GridPotentialFlow"
uuid = "1f0d46c9-1630-4f7c-9a63-ed825740f08c"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>", "Diederik Beckers <diederikbeckers@g.ucla.edu>"]
repo = "https://github.com/JuliaIBPM/GridPotentialFlow.jl"
version = "0.1.0"

[deps]
CartesianGrids = "3e975e5d-2cf8-4263-9573-8460aaf534d9"
ConstrainedSystems = "c257ce95-4918-4279-a47c-50fdbcb74a04"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RigidBodyTools = "befc5f09-81d5-499c-a4b2-d0464ba9f9c8"

[compat]
CartesianGrids = "0.1"
ConstrainedSystems = "0.1"
Reexport = "0.2"
RigidBodyTools = "0.1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
